version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.6
        environment:
          MIX_ENV: test

    working_directory: ~/repo
    steps:
      - checkout
      - run: mix local.hex --force  # install Hex locally (without prompt)
      - run: mix local.rebar --force  # fetch a copy of rebar (without prompt)

      # specify any bash command here prefixed with `run: `
      - run: mix do deps.get, compile
      - run: mix test
      - run: MIX_ENV=prod mix compile
